services:
  cdn:
    build:
      context: ./cdn
      dockerfile: Dockerfile
    image: ratterscanner/cdn:latest
    container_name: ratterscanner_cdn
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
    - "${STORAGE_DIR:-./sample_data}:/storage"